run:
  issues-exit-code: 1
  tests: true
  concurrency: 4
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  skip-dirs-use-default: false

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - revive
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/nancienta/api