version: 2

run:
  timeout: 5m
  concurrency: 4
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  skip-dirs-use-default: false

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor

linters:
  enable:
    - govet
    - revive
    - staticcheck