version: '3.8'
services:
  #  account_svc:
  #    build: ./services/account-svc
  #    environment:
  #      - DB_URL=${DB_URL}
  #    ports:
  #      - "9000:9000"
  #
  #  app_svc:
  #    build: services/application-svc
  #    environment:
  #      - DB_URL=${DB_URL}
  #    ports:
  #      - "9001:9001"
  #
  #  scaffold_svc:
  #    build: ./services/scaffold-svc
  #    ports:
  #      - "9002:9002"
  #
  #  logging_svc:
  #    build: ./services/logging-svc
  #    ports:
  #      - "9003:9003"

  redis:
    image: redis:latest
    ports:
      - "9379:9379"

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=nani
      - POSTGRES_PASSWORD=nani
      - POSTGRES_DB=postgres
    ports:
      - "9876:5432"